name: Heroku Awake

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://HEROKU_APP_NAME.herokuapp.com" 
          
      # Put Your Heroke App Name As it is in above line
      # Don't Change Any other Thing than App Name
